-- CREATE DATABASE if not EXISTS DATA;
-- USE DATA;
-- CREATE TABLE if not EXISTS PRODUCTS(
-- PID INT PRIMARY KEY,
-- NAME VARCHAR(40),
-- CATEGORY VARCHAR(20),
-- PRICE DECIMAL(10,2)
-- );
-- INSERT INTO PRODUCTS(PID,NAME,CATEGORY,PRICE)
-- VALUES
-- (101,'LAPTOP','ELECT',500.00),
-- (102,'MOBILE','ELECT',1000.00),
-- (103,'HEADPHONES','ELECT',200.00),
-- (104,'MOUSE','ELECT',300.000);

SELECT * FROM PRODUCTS;
SELECT NAME,PID FROM PRODUCTS ORDER BY PID DESC; 
SELECT NAME,PRICE FROM PRODUCTS WHERE PRICE BETWEEN 500 AND 1000; 
SELECT NAME,PRICE FROM PRODUCTS ORDER BY PRICE;
SELECT AVG(PRICE)AS AVG_TOTAL_REVENUE FROM PRODUCTS;
SELECT SUM(PRICE)AS TOTAL_REVENUE FROM PRODUCTS;